# Generated by Django 3.1.1 on 2021-04-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='cohort',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='park',
            old_name='capstone',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='park',
            name='favorite_teacher',
        ),
        migrations.RemoveField(
            model_name='park',
            name='favorite_topic',
        ),
        migrations.RemoveField(
            model_name='park',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='park',
            name='last_name',
        ),
    ]
