# Generated by Django 3.1.1 on 2021-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_auto_20210416_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='park',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
