# Generated by Django 3.1.1 on 2021-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0004_remove_park_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='place_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
