# Generated by Django 3.1.1 on 2021-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0006_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
